# Generated by Django 3.2 on 2021-05-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coursedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.IntegerField()),
                ('coursetitle', models.CharField(max_length=200)),
                ('coursename', models.CharField(max_length=200)),
                ('sectioncode', models.IntegerField()),
                ('coursedepartment', models.CharField(max_length=200)),
                ('instructorname', models.CharField(max_length=200)),
            ],
        ),
    ]
