# Generated by Django 3.2 on 2021-05-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalproj', '0003_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='studentfname',
            new_name='studentname',
        ),
    ]
